version: '2'

services:
  minestats:
    container_name: minestats
    ports:
      - 10119:8080
    build:
      context: .
    depends_on:
      - mongo
    environment:
      SPRING_DATA_MONGODB_HOST: ${SPRING_DATA_MONGODB_HOST}
      SPRING_DATA_MONGODB_PORT: ${SPRING_DATA_MONGODB_PORT}
      MINESTATS_LOCALE: ${MINESTATS_LOCALE}
      MINESTATS_FORUMURL: ${MINESTATS_FORUMURL}
      MINESTATS_NAME: ${MINESTATS_NAME}
      MINESTATS_TIMEZONE: ${MINESTATS_TIMEZONE}
      MINESTATS_CORECOUNT: ${MINESTATS_CORECOUNT}
      MINESTATS_QUERYIP: ${MINESTATS_QUERYIP}
      MINESTATS_QUERYPORT: ${MINESTATS_QUERYPORT}
      MINESTATS_AAYUSH_PAYPALDONATE: ${MINESTATS_AAYUSH_PAYPALDONATE}
      MINESTATS_AAYUSH_DB_USER: ${MINESTATS_AAYUSH_DB_USER}
      MINESTATS_AAYUSH_DB_PASSWORD: ${MINESTATS_AAYUSH_DB_PASSWORD}
      MINESTATS_AAYUSH_DB_URL: ${MINESTATS_AAYUSH_DB_URL}
      MINESTATS_AAYUSH_DB_DATABASENAME: ${MINESTATS_AAYUSH_DB_DATABASENAME}
      MINESTATS_MONTHLYDONATIONS: ${MINESTATS_MONTHLYDONATIONS}
      MINESTATS_MULTICRAFT_APIURL: ${MINESTATS_MULTICRAFT_APIURL}
      MINESTATS_MULTICRAFT_USER: ${MINESTATS_MULTICRAFT_USER}
      MINESTATS_MULTICRAFT_KEY: ${MINESTATS_MULTICRAFT_KEY}
      MINESTATS_MULTICRAFT_SERVERID: ${MINESTATS_MULTICRAFT_SERVERID}
      MINESTATS_BITBUCKET_APIURL: ${MINESTATS_BITBUCKET_APIURL}
      MINESTATS_BITBUCKET_APITOKEN: ${MINESTATS_BITBUCKET_APITOKEN}
      MINESTATS_BITBUCKET_ZONEID: ${MINESTATS_BITBUCKET_ZONEID}
    restart: unless-stopped
    networks:
      - default
  mongo:
    container_name: minestats_MongoDB
    image: mongo:latest
    ports:
      - 10120:27017
    volumes:
      - /var/docker/minestats/mongodb:/data/db
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_INITDB_ROOT_USERNAME}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_INITDB_ROOT_PASSWORD}
    restart: unless-stopped
    networks:
       - default
    command: mongod --bind_ip_all

networks:
  default:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.23.0.0/16